FROM node:16-alpine as build

WORKDIR /app

# Copier les fichiers minimaux
COPY minimal.html ./build/index.html

FROM nginx:alpine

# Copier les fichiers minimaux dans Nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]